Module2 task2
htmlacademy-php/1488503-doingsdone-12 pull request #6
Opened 2020-10-14 10:54 UTC by Obyedkov

2021-01-15 11:46 UTC, Obyedkov reviewed
написал функции getArrCount

2021-01-15 13:00 UTC, dshemin requested changes

2021-01-15 13:00 UTC, dshemin commented on index.php
> +    foreach ($arr as $in_ar)
Всегда оборачивайте тело `if`, `for', и т.д. в фигурные скобки, даже если там один оператор.

2021-01-17 20:26 UTC, Obyedkov commented on index.php
> +function getArrCount($arr, $depth = 1)
Я долго пытался понять слово type hinting, означает контроль типа. Искал в интернете там много объяснение класс ООП, я это не проходил, есть какие нибудь ссылки или где можно найти информацию?

2021-01-17 20:31 UTC, dshemin commented on index.php
> +function getArrCount($arr, $depth = 1)
https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.scalar-type-declarations
https://www.php.net/manual/en/migration71.new-features.php
https://mlocati.github.io/articles/php-type-hinting.html
https://phpenthusiast.com/object-oriented-php-tutorials/type-hinting

2021-01-19 07:39 UTC, Obyedkov commented on index.php
> +function getArrCount($arr, $depth = 1)
Спасибо, прочитал, все понятно.

Есть у меня сомнение, еще раз уточняю.
Ты написал что 
"Обратите внимание на задание: Функция должна принимать в качестве второго аргумента название проекта"

function getArrCount($arr, $depth = 1)

В качестве второго аргумента это $depth=1 надо поменять название проекта $task_table, я правильно понял?

2021-01-19 08:25 UTC, dshemin requested changes

2021-01-19 08:25 UTC, dshemin commented on index.php
> +function getArrCount($arr, $depth = 1)
Да, правильно. Но вместо `$task_table` лучше использовать `$category` более понятно по названию аргумента что он делает.

2021-01-20 18:08 UTC, dshemin requested changes

2021-01-20 18:08 UTC, dshemin commented on index.php
> +function getArrayCount ($tasks, $category){
`getArrayCount` слишком общее название из которого понять что делает функция трудно. Надо стремится давать имена переменным и функциям такие, чтобы по ним было понятно для чего они тут. В данном примере лучше назвать `countTasksForCategory`.

2021-01-20 18:08 UTC, dshemin commented on index.php
> +                        <?php if ($show_complete_tasks == 1):?><?php endif;?>
Не совсем понял зачем это тут.
1. Данная строчка ничего не делает. В независимости от значения `$show_complete_tasks` ничего не будет.
2. Ломается задание https://up.htmlacademy.ru/php/12/check/tasks/1488503/4

2021-01-20 18:08 UTC, dshemin commented on index.php
> +                    <?php if ($show_complete_tasks == 0)continue;?>
Не совесем понял зачем нам тут это условие. Вместе с ним, получается что если нам не надо показывать завершённые задачи, то мы не покажем вообще все задачи. В любом случае, в рамках данного упражнения, трогать это место не надо. Верните пожалуйста логгику как было сделано в предыдущих упражнениях.

2021-01-21 13:30 UTC, dshemin requested changes

2021-01-21 13:30 UTC, dshemin commented on index.php
> +function getArrayCount ($tasks, $category){
Обратите внимание на этот комментарий пожалуйста.

2021-01-21 13:30 UTC, dshemin commented on index.php
> +                        <input class="checkbox__input visually-hidden show_completed" type="checkbox">
Удалите лишную строкую

2021-01-21 13:46 UTC, dshemin requested changes

2021-01-21 13:46 UTC, dshemin commented on index.php
> +function countTasksForCategory ($tasks, $categories){
`categories` это множественное число от `category`. Тут у нас всегда будет одна категория. Поменяйте на `category`.

2021-01-21 16:02 UTC, dshemin approved these changes

2021-01-22 14:31 UTC, merged